services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && hoop run --name railsc-embedded-demo --data-masking EMAIL_ADDRESS,URL --command 'rails console' -- bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      HOOP_KEY: $HOOP_KEY
      CONTENT: the sensitive content (test-email@domain.tld) will be redacted
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
