services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      ADMIN_EMAIL: admin@domain.tld
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  hoop:
    build: .
    volumes:
      - .:/myapp
    command: hoop run --name railsc-demo --command 'rails console' --data-masking EMAIL_ADDRESS,URL
    environment:
      HOOP_KEY: $HOOP_KEY
      CONTENT: the sensitive content (test-email@domain.tld) will be redacted
